#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Time-stamp: <2024-03-22 20:10:00 krylon>
#
# /data/code/python/cephalopod/test_example_feed.py
# created on 22. 03. 2024
# (c) 2024 Benjamin Walkenhorst
#
# This file is part of the Wetterfrosch weather app. It is distributed
# under the terms of the GNU General Public License 3. See the file
# LICENSE for details or find a copy online at
# https://www.gnu.org/licenses/gpl-3.0

"""
cephalopod.test_example_feed

(c) 2024 Benjamin Walkenhorst
"""

from typing import Final

EXAMPLE_FEED: Final[str] = """
<?xml version="1.0" encoding="UTF-8" standalone="no"?><rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:googleplay="http://www.google.com/schemas/play-podcasts/1.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:media="http://search.yahoo.com/mrss/" xmlns:podcast="https://podcastindex.org/namespace/1.0" xmlns:psc="http://podlove.org/simple-chapters" version="2.0">
  <channel>
    <atom:link href="https://pubsubhubbub.appspot.com/" rel="hub"/>
    <atom:link href="https://sternengeschichten.podigee.io/feeds/scienceblogs/mp3" rel="self"/>
    <atom:link href="https://sternengeschichten.podigee.io/feeds/scienceblogs/mp3" rel="first"/>
    <atom:link href="https://sternengeschichten.podigee.io/feeds/scienceblogs/mp3?page=1" rel="last"/>
    <title>Sternengeschichten</title>
    <language>de</language>
    <pubDate>Wed, 05 Dec 2018 00:00:00 +0000</pubDate>
    <lastBuildDate>Fri, 22 Mar 2024 06:00:00 +0000</lastBuildDate>
    <description>Das Universum ist voll mit Sternen, Galaxien, Planeten und jeder Menge anderer cooler Dinge. Jedes davon hat seine Geschichten und die Sternengeschichten erzählen sie. Jeden Freitag gibt es eine neue Folge - das Universum bietet genug Material für immer neue Geschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten)</description>
    <link>http://sternengeschichten.org</link>
    <generator>Podigee (https://podigee.com)</generator>
    <itunes:type>episodic</itunes:type>
    <image>
      <url>https://images.podigee-cdn.net/0x,sdKDv5JgzCYubAQQ6apzLmR-MwPu8fBF-yF8RakvH-z4=/https://main.podigee-cdn.net/uploads/u4340/da452cf3-4bcc-4d33-a399-714e1497d3bb.jpg</url>
      <title>Sternengeschichten</title>
      <link>http://sternengeschichten.org</link>
    </image>
    <itunes:image href="https://images.podigee-cdn.net/0x,sdKDv5JgzCYubAQQ6apzLmR-MwPu8fBF-yF8RakvH-z4=/https://main.podigee-cdn.net/uploads/u4340/da452cf3-4bcc-4d33-a399-714e1497d3bb.jpg"/>
    <itunes:subtitle>Das Universum ist voll mit Sternen, Galaxien, Planeten und jeder Menge anderer cooler Dinge. Jedes davon hat seine Geschichten und die Sternengeschichten erzählen sie. Jeden Freitag gibt es eine neue Folge - das Universum bietet genug Material für immer n</itunes:subtitle>
    <itunes:author>Florian Freistetter</itunes:author>
    <itunes:explicit>no</itunes:explicit>
    <itunes:keywords>Science,Astronomy,Physics,Astronomie,Wissenschaft,Universum,Sterne,Planeten,Asteroiden,Sternengeschichten</itunes:keywords>
    <itunes:category text="Science"/>
    <itunes:category text="Society &amp; Culture"/>
    <itunes:category text="Education"/>
    <itunes:summary>Das Universum ist voll mit Sternen, Galaxien, Planeten und jeder Menge anderer cooler Dinge. Jedes davon hat seine Geschichten und die Sternengeschichten erzählen sie. Jeden Freitag gibt es eine neue Folge - das Universum bietet genug Material für immer neue Geschichten. Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten)</itunes:summary>
    <itunes:owner>
      <itunes:name>Florian Freistetter</itunes:name>
      <itunes:email>florian@astrodicticum-simplex.de</itunes:email>
    </itunes:owner>
    <podcast:guid>47d3dbf1-f7ca-52bc-82f8-0e2c3e2e1c02</podcast:guid>
    <item>
      <title>Sternengeschichten Folge 591: Lentikuläre Galaxien</title>
      <itunes:title>Sternengeschichten Folge 591: Lentikuläre Galaxien</itunes:title>
      <description>Wir leben in einer Spiralgalaxie. Es gibt aber auch Galaxien ohne Spiralarme. Wie diese lentikulären Galaxien entstanden sind, ist immer noch ungeklärt. Was wir trotzdem wissen, erfahrt ihr in der neuen Folge der Sternengeschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten</description>
      <pubDate>Fri, 22 Mar 2024 06:00:00 +0000</pubDate>
      <link>https://sternengeschichten.podigee.io/591-sternengeschichten-folge-591-lentikulare-galaxien</link>
      <guid isPermaLink="false">ba43dde5b0b6e88fad67611355044cb1</guid>
      <content:encoded>
        <![CDATA[Mysteriöse Sternenlinsen
<p><strong>Sternengeschichten Folge 591: Lentikuläre Galaxien</strong></p>
<p>Lentikuläre Galaxien werden auch linsenförmige Galaxien genannt und man nennt sie deswegen so, weil sie linsenförmig aussehen. Vielen Dank fürs Zuhören, bis zum nächsten Mal! Nein, es geht natürlich weiter. Denn die lentikulären Galaxien haben noch mehr zu bieten. Dazu müssen wir uns aber noch einmal kurz ansehen, was sie von anderen Galaxien unterscheidet. Ich habe in Folge 33 der Sternengeschichten schon mal einen kurzen Überblick über die Galaxienarten gegeben, aber vielleicht schauen wir uns das noch einmal schnell an.</p>
<p>Also: Es gibt erstmal zwei grundlegend unterschiedliche Arten von Galaxien, nämlich elliptische Galaxien und Spiralgalaxien. Elliptische Galaxien sind im Wesentlichen große, kugelförmige Haufen von Sternen. Diese Haufen können komplett kugelförmig sein oder mehroder weniger ellipsoid, also quasi abgeflachte Kugeln. Spiralgalaxien sind das, an was wir meistens denken, wenn wir uns eine Galaxie vorstellen: Eine flache Scheibe, in der sich die Spiralarme befinden und in der Mitte eine kugelförmige Region, in der die Sterne sehr dicht beieinander stehen, der Bulge. Unsere Milchstraße ist genau so eine Spiralgalaxie und zwar eine Balkenspiralgalaxie. In dieser Untergruppe wächst aus dem Bulge noch eine balkenartige Struktur aus Sternen, aus der dann die Spiralarme wachsen. Es gibt auch noch die irregulären Galaxien, deren Form - wie der Name sagt  - irregulär ist. Aber die sollen uns hier nicht beschäftigen, ich erwähne sie nur der Vollständigkeit halber.</p>
<p>Man bekommt all die unterschiedlichen Galaxienformen oft als Diagramm gezeigt, in der die elliptischen Galaxien entlang einer Linie angeordnet sind, von den komplett kugelförmigen bis hin zu den ganz stark abgeflachten. Von dort zweigen dann zwei Linien ab, wie bei einer Stimmgabel und auf der einen findet man die unterschiedlichen Formen der Spiralgalaxien und auf der anderen die entsprechenden Balkenspiralgalaxien. Das sieht dann oft so aus, als wäre das eine Entwicklungssequenz; so, als würde jede Galaxien als kugelförmige elliptische Galaxie beginnen, dann im Laufe der Zeit immer flacher werden bis sie sich irgendwann zu einer Spiral- oder Balkenspiralgalaxie entwickelt. Das ist definitiv nicht so; genau genommen ist es sogar umgekehrt, denn die elliptischen Galaxien können entstehen, wenn Spiralgalaxien miteinandern kollidieren und verschmelzen. Trotzdem gibt es diese Diagramme immer noch und am Schnittpunkt, dort wo elliptische auf die Abzweigungen zu den Spiralgalaxien treffen, findet man meistens einen Galaxientyp eingetragen, der mit "S0" bezeichnet wird. Genau das sind die Lentikulären Galaxien. </p>
<p>In den linsenförmigen Galaxien sind die Sterne in einer Scheibe angeordnet, so wie in den Spiralgalaxien auch. Nur gibt es dort keine Spiralarme, es ist einfach eine flache Scheibe aus Sternen; ein bisschen so ein Mittelding zwischen elliptischen und Spiralgalaxien. So weit, so klar. Was weit weniger klar ist, ist die Entstehungsgeschichte dieser Galaxienart. Wie elliptische Galaxien entstehen können, wissen wir halbwegs, das habe ich vorhin schon erwähnt. Wenn zwei Spiralgalaxien kollidieren, dann verschmelzen sie im Laufe von Milliarden von Jahren und bilden einen großen Haufen von Sternen, eine elliptische Galaxie. Und als damals im jungen Universum aus gigantischen Gaswolken die ersten Sterne beziehungsweise eben die ersten Galaxien entstanden sind, waren das vor allem erstmal irreguläre Galaxien, in denen sich erst im Laufe der Zeit und durch weitere Verschmelzungen die Spiralarme ausgebildet haben. Aber die irregulären Galaxien wollte ich ja auslassen. Ich lasse auch die Details der Entstehung der Spiralarme aus, was aber wichtig ist, ist die Tatsache, dass die Spiralarme vor allem aus jungen Sternen bestehen. Spiralarme sind keine "fixen" Strukturen; man darf sie sich nicht vorstellen wie die Speichen eines Fahrrads. Durch das ganze gravitative Wirrwarr in einer Galaxie aus hunderten Milliarden Sternen gibt es "Dichtewellen", also Bereiche, wo die kombinierte Gravitationskraft dazu führt, dass Gaswolken kollabieren und zu jungen, hell leuchtenden Sternen werden. Und weil sich alles in so einer Galaxie ständig bewegt, wandern immer wieder Gaswolken in diese Bereiche, dort entstehen Sterne, die wieder weiterziehen, aber durch neue junge Sterne ersetzt werden, die aus neuen Gaswolken entstehen, die in diese Dichteregionen wandern. Solange es noch genug Gas gibt, aus dem Sterne entstehen können, wird es also auch immer junge Sterne geben, die die Spiralarme quasi ausleuchten.</p>
<p>Lentikuläre Galaxien haben keine Spiralarme und daraus folgt, dass dort auch kaum noch neue Sterne entstehen. Ist die Sache damit jetzt also schon geklärt? Wir fangen mit einer Spiralgalaxie an, die wird immer älter und älter, irgendwann ist das ganze Gas für die Sternentstehung verbraucht und dann verblassen quasi die Spiralarme. Dazu passt auch folgender Befund: Wenn wir schauen, wo im Universum die Lentikulär-Galaxien zu finden sind, dann sehen wir sie vor allem in unserer Nähe. Oder anders herum gesagt: Wenn wir Galaxien betrachten, deren Licht sehr, sehr lange bis zu uns gebraucht hat; die also aus der Frühzeit des Universum stammen, finden wir dort kaum lentikuläre Galaxien. Oder noch einmal anders herum gesagt: lentikuläre Galaxien scheinen ein Phänomen des gegenwärtiges Universums zu sein; in der Vergangenheit hat es sie nicht gegeben. Was wiederum die Annahme unterstützt, dass es Zeit braucht, bis sie sich bilden und es sich um ausgeblichene Spiralgalaxien handelt. </p>
<p>Es könnte aber auch genau anders herum sein. Wir wissen, dass Galaxien einander immer wieder in die Quere kommen. Unsere Milchstraße und ihre Nachbargalaxie, die Andromedagalaxie, sind zum Beispiel gerade dabei, miteinander zu kollidieren. Der Vorgang dauert ein paar Milliarden Jahre, aber am Ende werden beide zu einer großen elliptischen Galaxie verschmolzen sein. So eine Wechselwirkung zwischen zwei Spiralgalaxien kann aber auch anders ablaufen. Wenn sie sich nahe kommen, wirken zwischen ihnen enorme Gezeitenkräfte. Dann verformen sie sich; die Spiralarme verformen sich und können regelrecht aufgedröselt werden und auch das Gas, aus dem Sterne entstehen können, kann aus den Galaxien rausgerissen werden. Am Ende kriegt man eine Galaxie ohne Spiralarme und ohne Gas, aus dem neue Sterne entstehen können, die neue Spiralarme bilden könnten.</p>
<p>Auch für diese Hypothese gibt es Beobachtungsdaten, die das stützen. Wenn wir uns große Galaxienhaufen anschauen; also die gewaltigen Ansammlungen aus hunderten oder bis zu hunderttausenden Galaxien. Dort finden wir alle möglichen Formen, auch die lentikulären Galaxien. Die sind in diesen Haufen aber vor allem in den inneren Regionen der Haufen, also dort, wo die Galaxien am dichtesten stehen und am ehesten miteinander wechselwirken können.</p>
<p>Beide Hypothesen haben ihre Stärken. Beide haben auch ihre Schwächen. Die Hypothese mit den wechselwirkenden Spiralgalaxien hat vielleicht ein paar mehr Stärken als Schwächen als die Verschmelzungshypothese. Zum Beispiel wenn man sich anschaut, wie schnell die Linsengalaxien rotieren und das mit ihrer Helligkeit vergleicht. Zwischen beiden Größen gibt es bei den normalen Spiralgalaxien einen Zusammenhang, nämlich die "Tully-Fisher-Beziehung" und der selbe Zusammenhang findet sich, leicht verschoben, auch bei den Lentikulärgalaxien. Aber auch das ist kein definitiver Beleg. </p>
<p>Wie die komischen Galaxien ohne Spiralarme entstehen, wissen wir noch nicht. Aber sie sind dort draußen, sie sind ein Teil unseres Universums und deswegen werden wir nicht aufhören, auch sie verstehen zu wollen.</p>]]>
      </content:encoded>
      <itunes:image href="https://images.podigee-cdn.net/0x,sIR4by5z_hyFq-A8cWp5upr4iA5_n4GnQWYK9makNmnY=/https://main.podigee-cdn.net/uploads/u4340/d9da3809-0d1b-4d2b-b7a9-ec9d3b70f28e.jpg"/>
      <itunes:episode>591</itunes:episode>
      <itunes:episodeType>full</itunes:episodeType>
      <itunes:subtitle>Mysteriöse Sternenlinsen</itunes:subtitle>
      <itunes:summary>Wir leben in einer Spiralgalaxie. Es gibt aber auch Galaxien ohne Spiralarme. Wie diese lentikulären Galaxien entstanden sind, ist immer noch ungeklärt. Was wir trotzdem wissen, erfahrt ihr in der neuen Folge der Sternengeschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten</itunes:summary>
      <itunes:explicit>no</itunes:explicit>
      <itunes:keywords>Astronomie,Universum,Sternengeschichten,Astrodicticum,Sterne,Galaxien,Galaxientyp,Morphologie,Elliptische Galaxie,Spiralgalaxie,Lentikulärgalaxie,Linsengalaxie,lentikuläre Galaxie,Galaxienkollision,wechselwirkende Galaxien,Sternentstehung,Spiralarme,Galaxienhaufen</itunes:keywords>
      <itunes:author>Florian Freistetter</itunes:author>
      <enclosure length="7785947" type="audio/mpeg" url="https://audio.podigee-cdn.net/1385415-m-50009a16ea151d4b12a4991c86cd38b4.mp3?source=feed-scienceblogs"/>
      <itunes:duration>538</itunes:duration>
      <podcast:episode>591</podcast:episode>
    </item>
    <item>
      <title>Sternengeschichten Folge 590: Joseph Weber und der vielleicht erste Nachweis von Gravitationswellen</title>
      <itunes:title>Sternengeschichten Folge 590: Joseph Weber und der vielleicht erste Nachweis von Gravitationswellen</itunes:title>
      <description>2015 konnten Gravitationswellen das erste Mal nachgewiesen werden. Aber vielleicht hat es Joseph Weber schon 1969 geschafft. Wieso wir das nicht so genau wissen, erfahrt ihr in der neuen Folge der Sternengeschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten</description>
      <pubDate>Fri, 15 Mar 2024 06:00:00 +0000</pubDate>
      <link>https://sternengeschichten.podigee.io/590-sternengeschichten-folge-590-joseph-weber-und-der-vielleicht-erste-nachweis-von-gravitationswellen</link>
      <guid isPermaLink="false">7b8ba24cabedbab3dabfa87c65d64207</guid>
      <content:encoded>
        <![CDATA[Pionier ohne Erfolgserlebnis
<p><strong>Sternengeschichten Folge 590: Joseph Weber und der vielleicht erste Nachweis von Gravitationswellen</strong></p>
<p>Gravitationswellen! Darüber habe ich in den Folgen 102 und 184 der Sternengeschichten schon ausführlich gesprochen. Dieses Phänomen war lange Zeit reine Theorie. Albert Einstein hat zu Beginn des 20. Jahrhunderts vorhergesagt, dass es so etwas geben muss und es hat auch eigentlich niemand daran gezweifelt, dass es tatsächlich existiert. Woran man aber immer wieder sehr wohl gezweifelt hat, war die Frage, ob man die Gravitationswellen irgendwann auch nachweisen wird können. </p>
<p>Aber fangen wir vielleicht noch einmal mit einer ganz kurzen Wiederholung an. Was sind Gravitationswellen? Wir wissen, dass der Raum nicht einfach nur ein abstraktes Dinges ist, sondern ein reales physikalisches Objekt. Der Raum kann vor allem gekrümmt werden und Albert Einstein hat uns nicht nur erklärt, dass die Anwesenheit von Masse den Raum  krümmt, sondern wir diese Raumkrümmung als Gravitationskraft wahrnehmen. Die Erde bewegt sich nicht deswegen um die Sonne, weil da irgendeine mysteriöse Kraft wirkt. Oder halt doch, irgendwie. Die Sonne krümmt den Raum und die Erde muss bei ihrer Bewegung dieser Raumkrümmung folgen und umkreist die Sonne deshalb, was für uns so aussieht, wie eine Kraft, die zwischen beiden Himmelskörpern wirkt. Damit ist auch eine Frage beantwortet worden, die vor Einstein nicht beantwortet werden konnte: Wie schnell breitet sich die Gravitationskraft aus? Isaac Newton hat noch gesagt, dass sie unendlich schnell wirkt. Wenn die Sonne verschwindet, würden wir auf der Erde sofort spüren, dass ihre Anziehungskraft weg ist. Einstein dagegen hat erklärt, dass sich die Krümmung des Raums nicht beliebig schnell verändern kann. Sondern nur mit Lichtgeschwindigkeit. Wenn also die Sonne verschwindet, dann dauert es 8 Minuten - so lange braucht Licht von der Sonne bis zu Erde - bis auch die veränderte Raumkrümmung sich bis zu uns ausgebreitet hat und wir das Verschwinden der Anziehungskraft merken. Oder anders gesagt: Wenn Massen sich in der Raumzeit bewegen (ganz genau: beschleunigt bewegen) verursacht das eine Veränderung in der Krümmung der Raumzeit und die breitet sich mit Lichtgeschwindigkeit aus. Es gibt also quasi Wellen im Raum selbst und genau das sind die Gravitationswellen. </p>
<p>Die Frage die noch bleibt ist: Wie kann man so was messen? Man kann ausrechnen, dass die Effekte winzig sind. Die Erde, die die Sonne umkreist, verursacht durch diese Bewegung Gravitationswellen. Zwei Sterne, die kollidieren, verursachen Gravitationswellen, ebenso wie ein Stern der explodiert oder zwei schwarze Löcher die zusammenstoßen. Wenn diese Wellen sich ausbreiten, dann sorgen sie dafür - sehr vereinfacht - dass der gesamte Raum gestreckt oder gestaucht wird. Wenn so eine Gravitationswelle auf die Erde trifft, dann wird unser Planet dadurch also ein klein wenig verformt. Und man kann sich denken, dass das ein sehr winziger Effekt ist, ansonsten hätten wir davon schon etwas mitbekommen, unter anderem, weil die Erde dabei kaputt gegangen wäre. Tatsächlich sorgen selbst extreme Ereignisse wie die Kollision zweier schwarzer Löcher nur für eine Verformung des Raums, die viel kleiner ist als der Durchmesser eines Atomkerns. Das zu messen ist enorm schwierig und man dachte, es wäre unmöglich. Aber wenn man immer so schnell aufgeben würde, würde in der Wissenschaft nichts vorwärts gehen. Das mag sich in den 1950er Jahren auch der amerikanische Physiker Joseph Weber gedacht haben. Der eigentlich einmal "Jonas" hieß; Webers Eltern sind aus Litauen nach Amerika ausgewandert und hießen ursprünglich "Gerber", aber daraus wurde dann "Weber" und aus Jonas irgendwann "Joseph". So oder so: Joseph Weber, 1919 geboren, ging nach seiner Schulzeit auf die Marineakademie, was deutlich billiger für ihn und seine Eltern war als der Besuch einer normalen Universität. Das führte aber auch dazu, dass Weber, nach seinem Abschluss 1940 als Offizier auf einem amerikanischen Flugzeugträger im zweiten Weltkrieg kämpfen musste. Sein Schiff wurde versenkt, aber Weber überlebte und kommandierte später selbst Schiffe. Nach dem Krieg begann er erneut zu studieren, weil er eine Stelle an einer Uni bekommen sollte, ihm dafür aber noch ein Doktortitel fehlte. Er begann zu Mikrowellentechnik zu forschen, war einer der Pioniere die sich mit der Physik von Lasern beschäftigte und war dafür auch für den Nobelpreis nominiert. Bekommen haben diesen Preis aber Kollegen; er selbst wurde bei der Auszeichnung für die Entwicklung des Lasers übergangen. </p>
<p>In den 1950er Jahren begann Weber sich für die Relativitätstheorie zu interessieren. Von 1955 bis 1956 war unter anderem bei John Wheeler zu Besuch, einem der wenigen Forscher, die sich damals intensiv mit der Gravitation im Rahmen von Einsteins Theorie beschäfigt haben. Dort lernte Weber auch die Gravitationswellen kennen und beschloss: Die Dinger müssen nachgewiesen werden! Also begann er in den 1960er Jahren, Detektoren zu bauen, die genau das tun sollten.</p>
<p>Aber wie baut man einen Gravitationswellendetektor? Man kann ja nicht einfach ein Lineal irgendwo hin legen und warten, ob es kürzer wird. Das müsste man ja mit einem anderen Lineal messen, das aber ebenfalls kürzer werden würde, wenn da eine Gravitationswellen durchsaust. Webers Idee sah so aus: Gravitationskraft wirkt auf Massen. Wir brauchen also auf jeden Fall mal ein Stück Masse. In Webers Fall war das zu Beginn ein großer Zylinder aus Aluminium, bis zu einem Meter im Durchmesser und bis zu zwei Meter lang. Dieser Zylinder war frei beweglich aufgehängt. Wenn jetzt eine Gravitationswelle durch die Erde und damit auch den Zylinder läuft; der Zylinder dadurch periodisch gestaucht und gestreckt wird, dann kann er dadurch zum Schwingen angeregt werden, was er auch dann noch tut, wenn die Gravitationswelle wieder weg ist. Wenn man den Zylinder also wackeln sieht, weiß man: Da ist ne Gravitationswelle gewesen.</p>
<p>In der Praxis ist das natürlich alles andere als einfach. Denn selbstverständlich wird der Zylinder durch eine Gravitationswelle nicht anfangen, wild hin und her zu schwingen. Es geht, wie gesagt, um Schwingungen in Bereichen, die kleiner als der Durchmesser eines Atomkerns sind. Das sieht man nicht mit freiem Auge. Aber Weber installierte Piezo-Elemente am Zylinder, also Geräte, die schon auf kleinste Veränderungen reagieren und dabei elektrischen Strom produzieren. Außerdem ging er sowieso nicht davon aus, jede Gravitationswelle messen zu können, sondern nur die, die gerade die richtige Frequenz haben, um die Eigenfrequenz des Zylinders anzuregen. Der Zylinder würde also stärker schwanken und die Messung des winzigen Effekts möglich machen. Trotzdem war es immer noch eine enorme Herausforderung. Allein das thermische Rauschen war groß genug, um den Effekt von Gravitationswellen zu überdecken. "Thermisches Rauschen" heißt in dem Fall, dass die Atome des Zylinders sich allein aufgrund der Temperatur bewegen und diese Bewegung in der gleichen Größenordnung ist oder größer ist, als der Effekt der Gravitationswellen. Weber installierte daher auch nicht nur einen Detektor, sondern mehrere an unterschiedlichen Orten der USA. Wenn der Zylinder nur wegen einer äußeren, lokalen Störung schwingt, dann würden die beiden Detektoren an den unterschiedlichen Orten das auch unterschiedlich tun. Aber wenn beide zur selben Zeit auf die selbe Weise reagieren, dann muss es ein globales Phänomen sein, zum Beispiel eine Gravitationswelle.</p>
<p>Genau so einen Ausschlag sah Weber im Juni 1969 in den Daten seiner beiden 1000 km voneinander entfernten Detektoren. Und er veröffentlichte eine Arbeit mit dem Titel "Hinweis auf die Entdeckung von Gravitationsstrahlung". Die Wissenschaft war aufgeregt und beeindruckt. Aber als dann andere anderswo ihre eigenen Detektoren bauten, konnte niemand Gravitationswellen damit messen. Weber meinte, die anderen Geräte wären nicht gut genug; die anderen meinten, Weber hätte sich geirrt. Es gab jede Menge Diskussion und Streit. Als ein andere Wissenschaftler Weber als Scharlaten bezeichnet hat, soll Weber geantwortet haben "Ich werde ihnen gleich zeigen, wozu ein Offizier der Marine fähig ist, den man Scharlatan nennt".</p>
<p>Weber jedenfalls forschte weiter und veröffentlichte Daten, die zeigten, dass er im Februar 1987 Gravitationswellen messen konnte. Und nicht einfach irgendwann im Februar 1987 sondern genau in dem Moment, als man auch die berühmte Supernova 1987A in der Magellanschen Wolke registriert hat. Die Teleskope der Astronomie sehen also einen explodierenden Stern und Weber misst zum gleichen Zeitpunkt eine Gravitationswelle, also genau das, was ein explodierender Stern verursacht. Aber auch hier war er der einzige, der die Welle gemessen hatte; andere Detektorne waren damals nicht in Betrieb und die Kolleginnen und Kollegen waren skeptisch. </p>
<p>Mittlerweile hatten andere Forscherinnen und Forscher eine andere Idee zum Nachweis der Gravitationswellen gehabt, nicht mit schwingenden Metallzylindern, sondern durch kilometerlange unterirdische Tunnel, in denen Lichtstrahlen hin und her reflektiert werden; in unterschiedliche Richtungen aber genau aufeinander abgestimmt. Sollte eine Gravitationswelle durch die Konstruktion hindurchlaufen, dann würden die Lichtstrahlen in der einen Richtung einen leicht kürzeren oder längeren Weg zurück legen müssen und das würde man dann merken. Auch hier waren die technischen Herausforderungen massiv und es hat Jahrzehnte gedauert, bis diese Gravitationswellenobservatorien einsatzbereit waren. Aber dann ist es damit im Jahr 2015 tatsächlich gelungen, die Existenz von Gravitationswellen einwandrei und ohne Zweifel nachzuweisen. Joseph Weber war zu diesem Zeitpunkt aber schon tot, er starb im September 2000. </p>
<p>Webers Arbeit mit seinen Detektoren war umstritten, aber Weber deswegen kein Außenseiter. Er bekam diverse Preise; man war beeindruckt von seinen kreativen Ideen und seiner enorm exakten Ingenieursarbeit. Vor allem aber hat er dafür gesorgt, dass die Forschung an Gravitationswellen von einem Randthema in der Physik zu einem populären Arbeitsgebiet geworden ist. Und vielleicht war er ja tatsächlich der erste, der sie auch nachweisen konnte. Die Astronomin Virgina Trimble, Webers zweite Ehefrau, wurde 2016 gefragt, ob sie glaube, dass ihr Mann Gravitationswellen gemessen hat. Ihre Antwort: "Ich weiß es nicht. Aber ich glaube, wenn es zwei Technologien gegeben hätte, die sich im Wettstreit zueinander vorangetrieben hätten – und nicht im Konkurrenzkampf – dann hätte man vielleicht schon früher Gravitationswellen beobachten können.“. Und der Physiker Kip Thorne, einer der drei, der für den Nachweis von Gravitationswellen den Nobelpreis bekommen haben, hat über Weber gesagt: "Joe ist in dieses Gebiet eingestiegen, als sonst niemand auf der Welt daran dachte“. Und so wichtig es auch ist, etwas zu entdecken: Es ist mindestens ebenso wichtig, bei etwas den Anfang zu machen.</p>]]>
      </content:encoded>
      <itunes:image href="https://images.podigee-cdn.net/0x,sUk3AlIhxUZOnJYvMmilCmYDQXYyPfeb4cjP2cYzC9tA=/https://main.podigee-cdn.net/uploads/u4340/8b19d67b-11c1-424c-805d-dd4a6163acc7.jpg"/>
      <itunes:episode>590</itunes:episode>
      <itunes:episodeType>full</itunes:episodeType>
      <itunes:subtitle>Pionier ohne Erfolgserlebnis</itunes:subtitle>
      <itunes:summary>2015 konnten Gravitationswellen das erste Mal nachgewiesen werden. Aber vielleicht hat es Joseph Weber schon 1969 geschafft. Wieso wir das nicht so genau wissen, erfahrt ihr in der neuen Folge der Sternengeschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten</itunes:summary>
      <itunes:explicit>no</itunes:explicit>
      <itunes:keywords>Astronomie,Universum,Sternengeschichten,Astrodicticum,Sterne,Relativitätstheorie,Gravitations,Gravitationswellen,Raumkrümmung,Joseph Weber,Gravitationswellendetektor,Resonanzdetektor,Marine,Albert Einstein,Kip Thorne,Virginia Trimble,Laser,Gravitationswellenobservatorium</itunes:keywords>
      <itunes:author>Florian Freistetter</itunes:author>
      <enclosure length="10596304" type="audio/mpeg" url="https://audio.podigee-cdn.net/1385413-m-e77061adc28247cbc13b9881860b422f.mp3?source=feed-scienceblogs"/>
      <itunes:duration>746</itunes:duration>
      <podcast:episode>590</podcast:episode>
    </item>
    <item>
      <title>Sternengeschichten Folge 589: Das Quark-Gluon-Plasma</title>
      <itunes:title>Sternengeschichten Folge 589: Das Quark-Gluon-Plasma</itunes:title>
      <description>Wo kommt die ganze Materie her? Aus dem Quark-Gluon-Plasma, dass in den erste Sekundenbruchteilen nach dem Urknall das Universum gefüllt hat. Was da genau passiert ist, erfahrt ihr in der neuen Folge der Sternengeschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten</description>
      <pubDate>Fri, 08 Mar 2024 06:00:00 +0000</pubDate>
      <link>https://sternengeschichten.podigee.io/589-sternengeschichten-folge-589-das-quark-gluon-plasma</link>
      <guid isPermaLink="false">dde5f39fc163718c32cafe9009ece1b2</guid>
      <content:encoded>
        <![CDATA[Der Ursprung von Allem
<p><strong>Sternengeschichten Folge 589: Das Quark-Gluon-Plasma</strong></p>
<p>In der heutigen Folge der Sternengeschichten geht es um das Quark-Gluon-Plasma. Das klingt ein wenig langweilig und vermutlich klingt es auch sehr unverständlich. Aber es lässt sich verstehen und man sollte es verstehen wollen, denn es ist alles andere als langweilig. Das Quark-Gluon-Plasma ist quasi der Ursprung von Allem. Und deswegen definitiv interessant.</p>
<p>Fangen wir mal damit an, was mit "Ursprung von Allem" gemeint ist. Nicht der Urknall, obwohl der auch eine kleine Rolle spielen wird. Der ist ja tatsächlich der Ursprung von Allem, schon per Definition. Der Urknall ist das Ereignis mit dem unser Universum begonnen hat, aber ganz so weit gehen wir nicht zurück. Wenn ich von "Allem" rede, dann meine ich die Materie. Die muss ja irgendwo her kommen. Ich habe in den Sternengeschichten schon oft darüber gesprochen, wie Planeten entstehen. Oder wie Sterne entstehen. Wie sich die großräumigen Strukturen aus Galaxien im Universum gebildet haben. Aber das meine ich heute nicht. Es geht auch nicht darum, wie die chemischen Elemente entstanden sind, also wie durch Kernfusion im Inneren der Sterne die verschiedenen Arten der Atome entstanden sind, der Sauerstoff, den wir atmen oder der Kohlenstoff aus dem wir bestehen. Es geht nicht einmal um die "primordiale Nukleosynthese", also die Phase, in der sich nach dem Urknall die simpelsten Elemente, nämlich Wasserstoff und Helium, gebildet haben, die die Grundlage für die Entstehung der ganzen anderen Elemente waren.</p>
<p>Wir gehen heute noch einen weiteren Schritt zurück. Jedes Atom besteht aus einem Atomkern und der besteht aus Protonen und Neutronen. Wenn wir also Materie haben wollen, brauchen wir die Dinger, dann brauchen wir Protonen und Neutronen. In dieser Folge werden wir uns anschauen, wie <em>diese</em> Atomkernbausteine entstanden sind und dafür müssen wir uns mit dem Quark-Gluon-Plasma beschäftigen.</p>
<p>Wenn wir verstehen wollen, was ein Quark-Gluon-Plasma ist, müssen wir verstehen, was Quarks sind, was Gluonen sind und was ein Plasma ist. Fangen wir mit dem letzten Begriff an: In der Physik bezeichnet man mit "Plasma" ein Gemisch aus Teilchen, das freie Ladungsträger enthält, in dem also geladenen Teilchen enthalten sind. Das muss nämlich nicht so sein. Wenn ich zum Beispiel einfach ein Gas betrachte, in dem sich Atome frei bewegen können, dann müssen diese Atome nicht elektrisch geladen sein und sind es auch meistens nicht. Aber wenn durch irgendwelche Prozesse zum Beispiel die elektrisch negativ geladenen Elektronen aus der Atomhülle vom elektrisch positiv geladenen Atomkern abgelöst werden und sich Kerne und Elektronen frei bewegen können, dann hat man ein Plasma. Beim Quark-Gluon-Plasma ist das nicht ganz so, aber das klären wir später noch. Schauen wir jetzt auf die ersten beiden Begriffe, auf Quarks und Gluonen.</p>
<p>Bei beiden handelt es sich um Elementarteilchen. Also um Bausteine der Materie von denen wir davon ausgehen, dass sie nicht aus irgendwelchen anderen Teilchen zusammengesetzt sind. Quarks gibt es in sechs verschiedenen Varianten, aber wenn es uns um die normale Materie geht, dann sind eigentlich nur zwei davon relevant, nämlich die Up-Quarks und die Down-Quarks. Wenn man zwei Up-Quarks und ein Down-Quark zusammensteckt, kriegt man ein Proton; bei zwei Down- und einem Up-Quark ist es ein Neutron. Und wie halten die Quarks zusammen? Durch die starke Kernkraft und die Gluonen sind die Teilchen, die diese Kraft vermitteln. Ich lasse jetzt sehr viel Teilchenphysik aus, aber vereinfacht gesagt tauschen die Quarks Gluonen aus und halten dadurch zusammen, so dass sie Protonen und Neutronen bilden. </p>
<p>Jetzt haben wir die Grundlagen geklärt, aber was wir eigentlich wissen wollen ist folgendes: Wann und wie sind im Universum die ersten Protonen und Neutronen entstanden? Dazu müssen wir bis fast zum Urknall zurück. Wir starten 100 Pikosekunden nach dem Beginn des Universums. Das sind 10 hoch minus 10 Sekunden beziehungsweise 0,00 00 00 00 01 Sekunden nach dem Urknall. Das ist wirklich kurz; in dieser Zeitspanne schafft es selbst das Licht nicht, sich weiter als drei Zentimeter fortzubewegen. Was in diesen 100 Pikosekunden seit dem Urknall passiert ist, lassen wir aus. Einerseits, weil die Wissenschaft selbst noch nicht genau weiß, was da alles abgegangen ist. Und andererseits weil das, was wir wissen, enorm kompliziert ist und den Rahmen dieser Folge sprengen würde. Also: Seit dem Urknall sind 100 Pikosekunden vergangen und der sehr junge Kosmos ist klein, extrem dicht und extrem heiß. Außerdem ist er voll mit Elementarteilchen, die gerade erst aus der Energie des Urknalls entstanden sind. Es gibt Quarks und Antiquarks; es gibt Elektronen und Anti-Elektronen und außerdem noch einen ganzen Haufen Neutrinos und Teilchen wie die Gluonen, die Kräfte zwischen ihnen vermitteln. Was es nicht gibt, sind Protonen und Neutronen und deswegen auch noch keine Atome. </p>
<p>Und weil das Universum so dicht war, sind die Quarks einander sehr nahe gekommen und haben sich mit Hilfe der Gluonen zu Protonen und Neutronen verbunden. Klingt plausibel. Aber das ist es nicht, was passiert ist. Denn die starke Kernkraft funktioniert ein wenig anders, als wir das von Kräften gewohnt sind. Wenn zum Beispiel zwei Massen sich gegenseitig mit ihrer Gravitationskraft anziehen, dann wird diese Kraft umso stärker, je näher sie sich kommen. Wenn wir zwei Magnete immer dichter aneinander schieben, wird die elektromagnetische Kraft zwischen ihnen immer stärker. Die starke Kernkraft, die zwischen den Quarks wirkt, funktioniert so aber nicht. Sie wird um so schwächer, je näher sich die Quarks sind. Das widerspricht unserer Intuition, aber unsere Intuition ist halt die Welt der kleinsten Teilchen nicht gewöhnt. Und alle Messungen und Beobachtungen zeigen uns genau das: Je näher sich zwei Quarks kommen, desto schwächer ist die starke Kernkraft zwischen ihnen.</p>
<p>Man kann sich das vielleicht so vorstellen: Wir haben einen Haufen Bälle, die durch Federn verbunden sind. Wenn die Bälle sich nahe sind, dann sind Federn nicht gespannt und die Bälle spüren keine Kraft dadurch und können sich frei hin und her bewegen. Wenn sie sich aber weit voneinander entfernen, werden die Federn gespannt und jetzt spüren sie eine Kraft von den anderen Bällen. Im jungen Universum jedenfalls waren die Temperaturen so hoch und die Teilchen so dicht aneinander gequetscht, dass sie die starke Kernkraft nicht gespürt haben. Sie sind wild durcheinander geflitzt und weil es nicht nur Teilchen gab, sondern auch Antiteilchen, haben sie sich immer wieder gegenseitig ausgelöscht. Außerdem waren nicht alle Teilchen stabil. Up- und Down-Quarks schon, genau so wie die Elektronen. Aber die anderen Arten der Quarks zum Beispiel nicht, die wandeln sich nach kurzer Zeit in andere Teilchen um, die stabiler sind. Die ganze Sache ist natürlich viel komplizierter als meine Geschichte hier, aber es läuft auf folgendes hinaus: Im Laufe der Zeit wandeln sich die instabilen Teilchen um; löschen sich diverse Teilchen und Antiteilchen aus. Von den Quarks bleiben irgendwann nur die stabilen Up- und Down-Varianten übrig. Und weil bei den Auslöschungs- und Zerfallsprozessen auch Photonen und Neutrinos entstehen, werden auch die im jungen Universum immer mehr und mehr. </p>
<p>Währenddessen dehnt sich das Universum immer weiter aus, es wird kühler und die Teilchen sind weniger dicht aneinander gequetscht. Und übrigens: Wir sind immer noch ganz am Anfang. Es sind jetzt vielleicht ein paar Mikrosekunden seit dem Urknall vergangen, aber es dauert immer noch, bis die erste Sekunde des Universums verstrichen ist. Auf jeden Fall haben die Quarks jetzt mehr Platz. Sie können sich weiter voneinander entfernen, unter Umständen sogar bis zu 10 hoch minus 15 Meter. Diese Distanz, ein Femtometer, ein Billiardstel von einem Meter, ist die Distanz, wo die starke Kernkraft für die Quarks spürbar wird. Oder anders gesagt: Die Quarks sind auf einmal nicht mehr frei! Sie hängen zusammen und je nachdem wie sie das tun, bilden sie Protonen oder Neutronen. Beziehungsweise auch andere Teilchen, die aber nicht stabil sind und nach kurzer Zeit zerfallen. </p>
<p>Ein paar Mikrosekunden nach dem Urknall hat sich dann alles ein wenig beruhigt. Das Universum ist jetzt voll mit gebundenen Quarks, die sich zur Protonen und Neutronen zusammengefunden haben. Außerdem ist es voll mit Energie in Form von Photonen, die bei den Zerfällen davor entstanden sind. Und Neutrinos und Elektronen sind natürlich noch auch noch übrig. Das, was jetzt im jungen Universum vorhanden ist, ist das, aus dem später alles andere entsteht. Diese Materie ist es, aus der sich dann ein paar Minuten später die Atomkerne von Wasserstoff und Helium bilden, die sich ein paar hunderttausend Jahre später mit den Elektronen zu kompletten Atomen verbinden aus denen dann ein paar Millionen Jahre danach die ersten Sterne entstehen. Aber angefangen hat alles in diesen ersten Sekundenbruchteilen, in der das Universum von einer wilden Mischung aus frei beweglichen, ungebundenen Quarks gefüllt war. Diesen Zustand nennt man "Quark-Gluon-Plasma" und aus diesem Zustand heraus sind die ersten Bausteine der Atomkerne entstanden.</p>
<p>Es gibt noch viel, was wir da besser verstehen müssen und viel, was wir noch gar nicht verstehen. Wir können diese ersten Sekundenbruchteile nach dem Urknall nicht direkt erforschen, aber wir können sie - tatsächlich - hier auf der Erde nachstellen. In Teilchenbeschleunigern können wir schwere Atomkerne so heftig aufeinander prallen lassen, dass für extrem kurze Zeit auf einem sehr begrenzten Raum ein Quark-Gluon-Plasma entsteht. Auch hier verbinden sich die freien Quarks natürlich sofort wieder zu anderen Teilchen, zerfallen, und so weiter. Aber für einen Sekundenbruchteil herrschen im Teilchenbeschleuniger in einem unvorstellbar kleinen Raum die selben Bedingungen wie kurz nach dem Urkannl. Und wenn wir die diese Zerfallsprodukte analysieren, die aus diesem künstlichen Quark-Gluonen-Plasma entstehen, verstehen wir vielleicht irgendwann auch besser, wie vor Milliarden Jahren alles angefangen hat.</p>]]>
      </content:encoded>
      <itunes:image href="https://images.podigee-cdn.net/0x,sGYgM0DqGoJGeh0h-Zq7PmXMR5bPrmRXFfxUQM8Sb_H8=/https://main.podigee-cdn.net/uploads/u4340/0522518f-1aba-4fb8-94f4-1cf0858d1ef9.jpg"/>
      <itunes:episode>589</itunes:episode>
      <itunes:episodeType>full</itunes:episodeType>
      <itunes:subtitle>Der Ursprung von Allem</itunes:subtitle>
      <itunes:summary>Wo kommt die ganze Materie her? Aus dem Quark-Gluon-Plasma, dass in den erste Sekundenbruchteilen nach dem Urknall das Universum gefüllt hat. Was da genau passiert ist, erfahrt ihr in der neuen Folge der Sternengeschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten</itunes:summary>
      <itunes:explicit>no</itunes:explicit>
      <itunes:keywords>Astronomie,Universum,Sternengeschichten,Astrodicticum,Sterne,Quark-Gluon-Plasma,Quarks,Gluonen,Plasma,Kosmologie,Quantenmechanik,Quanten-Epoche,Urknall,Protonen,Neutronen,starke Kernkraft,Quark-Confinement,Materie</itunes:keywords>
      <itunes:author>Florian Freistetter</itunes:author>
      <enclosure length="9630965" type="audio/mpeg" url="https://audio.podigee-cdn.net/1385412-m-e88b825eff797068e50c846518578a0e.mp3?source=feed-scienceblogs"/>
      <itunes:duration>677</itunes:duration>
      <podcast:episode>589</podcast:episode>
    </item>
    <item>
      <title>Sternengeschichten Folge 588: Fomalhaut - Der staubige Mund des Fisches</title>
      <itunes:title>Sternengeschichten Folge 588: Fomalhaut - Der staubige Mund des Fisches</itunes:title>
      <description>Der Stern Fomalhaut ist von jeder Menge Staub umgeben. Dort passieren wilde Dinge und wir können dabei zusehen. Was es da zu entdecken gibt, erfahrt ihr in der neuen Folge der Sternengeschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten</description>
      <pubDate>Fri, 01 Mar 2024 06:00:00 +0000</pubDate>
      <link>https://sternengeschichten.podigee.io/588-sternengeschichten-folge-588-fomalhaut-der-staubige-mund-des-fisches</link>
      <guid isPermaLink="false">494694d15c50d7fcbb51fa06b1847a46</guid>
      <content:encoded>
        <![CDATA[Staubscheiben und falsche Planeten
<p><strong>Sternengeschichten Folge 588: Fomalhaut - der staubige Mund des Fisches</strong></p>
<p>25 Lichtjahre von der Erde entfernt hat der Fisch sein riesiges Maul geöffnet. Denn das ist es, was der arabische Name des Sterns Fomalhaut bedeutet: Das "Maul des Fisches". Und passenderweise befindet sich der Stern auch im Sternbild "Südlicher Fisch". Von Mitteleuropa aus ist es und damit auch der Stern nur im Spätsommer zu sehen, aber Fomalhaut gehört zu den hellsten Sternen am Himmel; er ist der 18. hellste Stern, wenn man genau sein will. Er ist daher schon in den frühesten Sternkatalogen zu finden aber wie beeindruckend dieser Stern wirklich ist, haben wir erst in den letzten Jahrzehnten entdeckt, als wir ihn mit großen Teleskopen beobachtet haben.</p>
<p>Aber bleiben wir zuerst noch bei den Grundlagen. Fomalhaut ist hell; er leuchtet ungefähr 17 mal so hell wie unsere Sonne. Er ist auch knapp doppelt so groß und schwer wie unser Stern und dementsprechend heißer, mit einer Oberflächentemperatur von über 8000 Grad. Er gehört zum Spektraltyp A, das bedeutet, dass es sich um einen großen, heißen und noch recht jungen Stern handelt; Fomalhaut ist erst gut 400 Millionen Jahre alt und wie es bei so großen Sternen üblich ist, wird er auch nicht allzu lange existieren und nur knapp eine Milliarde Jahre alt werden.</p>
<p>Fomalhaut muss sein vergleichsweise kurzes Sternenleben aber nicht alleine verbringen; er ist Teil eines Dreifachsternsystems - allerdings eines, das ein wenig unüblich ist. Sein erster Partner ist der Stern TW Piscis Austrini, oder auch Fomalhaut B. Es handelt sich um einen kleineren, eher sonnenähnlichen Stern, der aber fast ein ganzes Lichtjahr von Fomalhaut entfernt ist. So große Distanzen sind bei Doppelsternen eher unüblich und der dritte Stern des Systems ist noch weiter entfernt. Fomalhaut C oder auch LP 876-10 ist ein kleiner roter Zwergstern mit einem Abstand von 2,5 Lichtjahren. Trotzdem hängen alle drei zusammen und das sie ein Mehrfachsystem bilden, bei dem die einzelnen Sterne so weit auseinander liegen, ist nicht die einzige Besonderheit. Aber dazu kommen wir später noch, jetzt werfen wir einen genaueren Blick auf Fomalhaut. </p>
<p>Schon 1983 hat man dort einen Infrarot-Exzess entdeckt. Und mit "Exzess" ist keine wilde Party gemeint, sondern ein Überschuss. Oder anders gesagt: Man hat mehr Infrarotstrahlung gesehen, als bei einem Stern wie Fomalhaut eigentlich zu erwarten war. Die Ursache dafür war schnell gefunden: Der Stern ist von einer Scheibe aus Staub umgeben. Dieser Staub wird durch die Strahlung des Sterns aufgeheizt und gibt die Wärme dann wieder ab, in Form von Infrarotstrahlung. Fomalhaut war einer der ersten Sterne, bei denen man so etwas entdeckt hat, aber bis man seine Staubscheibe auch im Detail sehen konnte, hat es noch ein wenig gedauert. Zum Glück haben wir mittlerweile viele Infraroteleskope im Weltall, die die Wärmestrahlung des Staubs detektieren und ein genaues Bild der Scheibe um Fomalhaut machen können. Beziehungsweise: Der Scheiben, denn es gibt mehrere. Der Stern ist von Staubringen umgeben von denen der innerste fast direkt am Stern dran ist. Die Staubteilchen dort sind sehr klein, nur ein paar Dutzend Nanometer groß. Größere Partikel gibt es weiter außen in einem Ring, der - wenn man ihn unser Sonnensystem versetzen würde, so breit wäre wie der Abstand zwischen den Umlaufbahnen von Merkur und Erde. Dann kommt eine Lücke und dann noch eine breite äußere Staubscheibe, die so breit ist wie fast das ganze Sonnensystem bis hin zur Umlaufbahn von Neptun und sich bei einem Abstand von gut 130 Astronomischen Einheiten befindet, also mehr als dreimal so weit, wie der Pluto von der Sonne entfernt ist. </p>
<p>Staub um einen Stern herum ist erstmal nicht außergewöhnlich. Alle Sterne fangen mit Staub an; sie entstehen ja aus großen Wolken voller Gas und Staub und davon bleibt immer ein bisschen was übrig, das sich dann in einer Scheibe um den jungen Stern herum ansammelt. Wir können die ganzen Staubteilchen natürlich nicht direkt sehen. Aber wie ich schon gesagt habe: Sie erwärmen sich durch die Strahlung des Sterns und sie geben die Wärme in Form von Infrarotstrahlung wieder ab. Und die Wellenlänge dieser Strahlung hängt von der Größe der Staubteilchen ab. Deswegen wissen wir auch, dass die Staubteilchen in der äußeren Scheibe circa ein paar Mikrometer groß sind. Und das ist interessant: Denn Staub dieser Art sollte eigentlich rein durch den Druck der Strahlung des Sterns quasi davon gepustet werden. Das geht vergleichsweise schnell und bei einem Alter von 400 Millionen Jahre sollte nichts mehr davon übrig sein. </p>
<p>Jetzt ist da aber noch was und zwar jede Menge und das bedeutet, dass dieser Staub immer wieder nach produziert werden muss. Das kann durch Kollisionen passieren: Wenn sich dort viele Asteroiden und Kometen tummeln, dann können die miteinander zusammenstoßen und dabei Staub produzieren. Aus den Beobachtungsdaten kann man ausrechnen, dass man ungefähr 10 Billionen Kometen mit einer typischen Größe von einem Kilometer braucht, um so viel Staub zu produzieren, wie man bei Fomalhaut beobachtet. Das klingt nach viel - das ist auch viel - aber es ist nicht unverhältnismäßig viel. Auch die Erde ist von einer Wolke aus Kometen umgeben - der Oortschen Wolke über die ich in Folge 321 mehr erzählt habe - und man schätzt, dass sich dort ebenfalls ein paar Billionen Objekte befinden. Wir wissen auch, dass sich die Objekte der Oortschen Wolke ursprünglich in einer Scheibe in den inneren Bereichen des Sonnensystems befunden haben und wir wissen, dass es auch bei uns heute noch Scheiben aus Asteroiden und Kometen gibt, die wir "Asteroidengürtel" nennen. Hinter der Bahn des Neptun ist zum Beispiel der Kuipergürtel und der muss bei der Entstehung des Sonnensystems eine gesamte Masse gehabt haben, die ungefähr dem 30fachen der Erdmasse entspricht. Bei Fomalhaut braucht man eine entsprechende Masse im Ring von 110 Erdmassen, was - wie gesagt - nicht unverhältnismäßig viel mehr ist.</p>
<p>Und wir dürfen nicht vergessen: Fomalhaut ist sehr viel jünger als die Sonne. Unser Stern ist 5 Milliarden Jahre alt; Fomalhaut erst 400 Millionen Jahre. Wir hatten sehr viel mehr Zeit, in der das ganze Zeug, das früher da war, in die Oortsche Wolke oder den interstellaren Raum verabschiedet hat. Fomalhaut sitzt, vereinfacht gesagt, immer noch in einer großen Menge des Staubs rum, aus dem er geboren worden ist. Obwohl, das ist schon fast zu vereinfacht. Wenn das so wäre, dann wäre da ja NUR Staub und das trifft vermutlich sogar auf die inneren Scheiben zu. In der äußeren Scheibe muss sich der Staub aber schon zu größeren Objekten, eben den Kometen und Asteroiden, zusammengeballt haben und die produzieren jetzt neuen Staub durch Kollision.</p>
<p>Aber wenn sich aus dem Staub Asteroiden und Kometen gebildet haben: Haben sich da vielleicht auch schon Planeten gebildet? Weil so ist es ja bei uns weitergegangen: Zuerst war nur Staub, dann Asteroiden und Kometen und daraus sind dann die Planeten entstanden. Und die Lücke zwischen den Staubringen bei Fomalhaut weißt auch darauf hin, dass da vielleicht schon größere Objekte sind, die mit ihrer Gravitationskraft den Staub durcheinander bringen. Tatsächlich hat man 2008 die Entdeckung eines Planeten bei Fomalhaut verkündet. Und nicht nur das, man hat diesen Planeten sogar gesehen. Das Hubble-Weltraumteleskop hat ein Bild gemacht, bei dem der Planet als kleiner Lichtpunkt inmitten der Staubringe von Fomalhaut zu sehen war. Ungefähr so halb so schwer wie Jupiter, und circa 114 mal weiter von seinem Stern entfernt als die Erde von der Sonne. Man hat dem Planeten den Namen "Dagon" gegeben, nach einem mesopotamischen Wetter-Gott, der als Fisch dargestellt wurde. Und wenn es Dagon wirklich geben würde, dann wäre er ein nicht nur enorm spannender Planet, sondern auch der erste Planet gewesen, den man direkt auf diese Art gesehen hätte.</p>
<p>Aber ich verwende nicht umsonst den Konjunktiv. Man hatte schon einige Jahre nach seiner Entdeckung vermutet, dass es vielleicht etwas anders ist; eventuell kein Planet sondern eine dichte Wolke aus Staub und Trümmern, die bei einer Kollision zwischen zwei größeren Asteroiden entstanden ist. Das konnte 2020 bestätigt werden: In den Daten der vergangenen Jahre sah man deutlich, dass der "Planet" immer größer wurde und gleichzeitig immer weniger hell leuchtete. Also genau das, was man erwartet, wenn sich eine Trümmerwolke im Laufe der Zeit immer weiter ausbreitet. </p>
<p>Das heißt nicht, dass es dort keine Planeten gibt. Aber entweder haben wir sie noch nicht entdeckt, oder aber sie müssen erst noch entstehen. Und wenn nicht dort, dann vielleicht bei Fomalhaut C. Denn auch bei dem kleinen, fernen Begleitstern hat man 2013 eine Staubscheibe entdeckt. Und auch dort hat man Hinweise auf die Existenz von Kometen und Asteroiden gefunden. Ich habe vorhin schon erwähnt, dass das Dreifachsternsystem wegen seiner großen Abstände außergewöhnlich ist; ein Dreifachsternsystem mit zwei Staubscheiben ist allerdings WIRKLICH was besonderes. Was auch immer da im Maul des Fisches passiert, wird die Astronomie noch lange Zeit beschäftigen.</p>]]>
      </content:encoded>
      <itunes:image href="https://images.podigee-cdn.net/0x,scnaUJ7vHb0ISC26aCVlgqb_QN_PS4tPNvEzeGxUOZCE=/https://main.podigee-cdn.net/uploads/u4340/de13a057-0028-48b4-b0f1-f83c124a0364.jpg"/>
      <itunes:episode>588</itunes:episode>
      <itunes:episodeType>full</itunes:episodeType>
      <itunes:subtitle>Staubscheiben und falsche Planeten</itunes:subtitle>
      <itunes:summary>Der Stern Fomalhaut ist von jeder Menge Staub umgeben. Dort passieren wilde Dinge und wir können dabei zusehen. Was es da zu entdecken gibt, erfahrt ihr in der neuen Folge der Sternengeschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten</itunes:summary>
      <itunes:explicit>no</itunes:explicit>
      <itunes:keywords>Astronomie,Universum,Sternengeschichten,Astrodicticum,Sterne,Fomalhaut,südlicher Fisch,TW Piscis Austrini,LP 876-10,Dreifachsternsystem,Staubscheibe,Protoplanetare Scheibe,Fomalhaut b,Trümmerscheibe,Oortsche Wolke,Kuipergürtel,Asteroiden,Kometen,Kollision,Exoplanet,Infrarotexzess,Dagon</itunes:keywords>
      <itunes:author>Florian Freistetter</itunes:author>
      <enclosure length="9226124" type="audio/mpeg" url="https://audio.podigee-cdn.net/1378566-m-c7fc4158fbfb043afb1456371dce4044.mp3?source=feed-scienceblogs"/>
      <itunes:duration>648</itunes:duration>
      <podcast:episode>588</podcast:episode>
    </item>
    <item>
      <title>Sternengeschichten Folge 587: Das Brummen der Erde</title>
      <itunes:title>Sternengeschichten Folge 587: Das Brummen der Erde</itunes:title>
      <description>Die Erde brummt. Das hören wir nicht, aber sie tut es trotzdem. Warum sie es tut und was wir daraus lernen können, erfahrt ihr in der neuen Folge der Sternengeschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten</description>
      <pubDate>Fri, 23 Feb 2024 06:00:00 +0000</pubDate>
      <link>https://sternengeschichten.podigee.io/587-sternengeschichten-folge-587-das-brummen-der-erde</link>
      <guid isPermaLink="false">2c4ce635804c986ac91fcf291dfc9ca2</guid>
      <content:encoded>
        <![CDATA[Alles schwingt, aber nicht esoterisch
<p><strong>Sternengeschichten Folge 587: Das Brummen der Erde</strong></p>
<p>Die Erde brummt. Das können wir nicht hören, aber sie tut es trotzdem. Und deswegen schauen wir uns heute das Erdbrummen, wie es umgangssprachlich genannt wird beziehungsweise die Eigenschwingungen der Erde, wie man es wissenschaftlich korrekt nennt, etwas genauer an. Über ein ähnliches Phänomen habe ich schon in Folge 164 gesprochen, als es um Asteroseismologie ging. Aber, wie der Name schon sagt, waren es damals schwingende Sterne, von denen ich erzählt habe. Schwingen tut aber auch die Erde und bevor wir uns das genauer anschauen, müssen wir erst einmal klären, was damit gemeint ist.</p>
<p>Stellen wir uns eine Kugel aus Metall vor und einen Hammer, mit dem wir auf diese Kugel schlagen. Was passiert ist klar: Es wird "Klong!" machen. Der Hammer hat die Kugel zum Vibrieren gebracht und dadurch wird auch die Luft in Vibration versetzt und wenn die dann auf unsere Ohren trifft, hören wir ein Geräusch. Oder stellen wir uns einen Wackelpudding vor, auf den wir mit einem Löffel schlagen. Auch dann wird der Pudding, ganz seinem Namen gerecht, hin und her wackeln. Ein Geräusch gibt es dabei nicht, oder besser gesagt: Es gibt kein Geräusch, das wir hören können, denn das Wackeln des Puddings ist zu langsam, als dass es ein für unsere Ohren hörbares Geräusch erzeugt. </p>
<p>Aber es geht ja heute um die Erde. Die ist weder eine Kugel aus Metall und auch nicht aus Pudding. Und es haut auch niemand mit einem riesigen Hammer oder einem großen Löffel auf sie ein. Aber sie schwingt trotzdem. Das merken wir zum Beispiel sehr deutlich, wenn ein Erdbeben stattfindet. Dann breiten sich Erdbebenwellen durch den Planeten aus und das ist ja nichts anderes als eine Schwingung im Gestein der Erde. Aber irgendwann ist so ein Erdbeben vorbei und die Wellen haben sich wieder beruhigt. Die Eigenschwingungen der Erde um die es heute geht, haben mit den Erdbeben allerdings erstmal nicht viel zu tun. Selbst wenn es einmal auf der ganzen Erde keine Erdbeben gibt, keine Vulkanausbrüche, und so weiter, schwingt der Planet trotzdem ein kleines bisschen.  Und damit ist wirklich ein kleines bisschen gemeint. Es geht um Bewegungen von ein paar Zehntausendestel Millimeter, die periodisch alle paar Minuten stattfinden. Das Geräusch das dabei entsteht ist erstens enorm schwach und zweitens weit tiefer als das, was unsere Ohren hören könnten. </p>
<p>Aber es gibt diese Bewegung. Es gibt sogar zwei Arten von Bewegungen beziehungsweise zwei grundlegend unterschiedliche Weisen, wie die Erde schwingen kann. Die erste nennt man "sphäroidale Schwingungen" und das klingt kompliziert. Das kann auch sehr kompliziert werden, aber im Grunde ist es ganz einfach. Wenn die Erde zum Beispiel einfach nur pulsiert, ist das eine sphäroidale Schwingung. "Pulsieren" heißt in diesem Fall, dass die Erde größer wird, kleiner wird, größer wird, kleiner wird, und so weiter. Wie gesagt, es geht hier um winzigste Änderungen, aber das Prinzip bleibt gleich. Dieses Pulsieren ist die einfachste Schwingung die die Erde durchführen kann, aber es geht auch komplexer. Sie kann zum Beispiel abwechselnd in unterschiedliche Richtungen schwingen. Stellen wir uns vor, wir würden die Erde zusammendrücken, sie quasi mit den Fingern an Nord- und Südpol fassen und dann ein bisschen quetschen. Dann lassen wir los, packen sie am Äquator und ziehen sie auseinander. Dann wird wieder an den Polen gedrückt, und so weiter. Die ganze Schwingerei kann noch viel komplexer werden, aber das ist das Prinzip der sphäroidalen Schwingung.</p>
<p>Es gibt aber auch noch toroidale Schwingungen. Hier können wir uns vorstellen, dass wir probieren, die Erde aufzuschrauben. Wir drehen also die Nordhalbkugel in die eine Richtung und die Südhalbkugel in die andere Richtung. Wenn wir dann loslassen, dreht sich die verdrillte Erde wieder zurück und hin und her, auf unterschiedlichen Hemisphären in unterschiedliche Richtungen. Wenn man es ganz stark und vermutlich zu stark vereinfachen möchte, dann sind sphäroidale Schwingungen welche, bei denen sich der Erdboden auf und ab bewegt und toroidale Schwingungen welche, bei denen sich der Erdboden horizontal hin und her bewegt.</p>
<p>Dass es so etwas geben kann, ist vorerst keine große Überraschung. Alles schwingt, wenn man es entsprechenden Kräften aussetzt. Bei der Sonne zum Beispiel haben wir diese Schwingungen schon in den 1960er Jahren beobachtet. Aber im Gegensatz zu unserem Stern ist die Erde keine Gaskugel sondern besteht aus fester Materie und hier wirken auch nicht die enormen Kräfte, die das Innere der Sonne beherrschen. Und außerdem gibt es andauernd Erdbeben, Vulkanausbrüche und so weiter, die die winzigen Eigenschwingungen unseres Planeten überlagern. Es ist lange Zeit fast unmöglich erschienen, das Erdbrummen zu messen und es hat tatsächlich bis 1998 gedauert, bis es das erste Mal gelungen ist. Kazunari Nawa und Naoki Suda von der Universität Nagoya in Japan haben das geschafft, aber auch nur, weil sie jahrelang gesammelte seismische Daten sehr genau analysiert und alle Störquellen rausgerechnet haben. Und das, was sie nachweisen konnten, waren nur die sphäroidalen Schwingungen; bis auch die toroidalen Schwingungen entdeckt werden konnten, hat es nochmal fast 10 Jahre gedauert. Dann konnte der deutsche Geophysiker Dieter Kurrle sie am Black Forest Observatory im Schwarzwald nachweisen. Dieses Observatorium befindet sich tief in einem alten Bergwerk; die Messinstrumente sind hinter hunderten Metern von Gestein abgeschirmt. Was auch dringend nötig ist, denn es reichen schon kleinste Störungen, um die Messung zu verhindern. Wenn zum Beispiel sich der Luftdruck ein klein wenig ändert. Oder die Temperatur. Und was passiert, wenn irgendwo ein Auto vorbei fährt, kann man sich vorstellen. Aber im Bergwerk des Schwarzwaldes, hinter luftdicht verschlossenen Schleusentüren ist die Messung gelungen. Aber auch nur, weil die Daten von dort mit denen aus ähnlichen Einrichtungen in China und Japan verglichen werden konnten. Nur wenn man überall auf der Welt konsistente Daten kriegt, kann man sicher sein, dass es sich um ein globales Phänomen handelt und keine lokale Störung.</p>
<p>Man darf sich das Erdbrummen übrigens nicht so vorstellen wie eine Glocke, die angeschlagen wird. Wie ich vorhin schon gesagt habe, gibt es ja nicht nur eine Schwingung, sondern jede Menge. Die überlagern sich alle, aber eben nicht so wie bei einem Musikinstrument, wo es einen Grundton gibt und diverse Obertöne, die alle harmonisch zusammenklingen. Beim Erdbrummen sind alle möglichen Frequenzen wild durcheinander gemischt und wenn man unbedingt eine musikalische Analogie finden will, dann eher die eines Orchesters, wo vor dem Konzert erstmal sämtliche Instrumente gestimmt werden und ohne Plan durcheinander klingen. </p>
<p>So, jetzt wissen wir, was das Erdbrummen ist. Aber was ist die Ursache? Warum tut die Erde das? Warum schwingt sie einfach so vor sich hin, auch ganz ohne Erdbeben oder andere große Ereignisse? Das ist eine gute Frage und eine, die schwer zu beantworten ist. Bei den sphäroidalen Schwingungen ist es noch vergleichsweise einfach. Da geht es ja um die Auf-und-Ab-Schwingung und man muss - sehr vereinfacht gesagt - nur auf die Erde drücken, damit das passiert. Und solche Druckkräfte gibt es: Zum Beispiel in der Atmosphäre, wenn sich der Luftdruck verändert. Oder in den Meeren, wenn der Wind Wellen erzeugt, die dann unter Umständen bis tief hinunter auf den Meeresboden drücken. Dass das eine Ursache sein kann, wird auch durch die Beobachtung gestärkt, dass sich das Erdbrummen im Rhythmus der Jahreszeiten verändert. Und im Winter gibt es ja tatsächlich sehr viel mehr und heftigere Stürme, mit entsprechend mehr Wellen. Die Ursache der toroidalen Schwingungen ist dagegen nicht so leicht zu erklären. Hier geht es ja um horizontale Bewegung, nicht um ein Auf und Ab sondern ein Hin und Her. Und dementsprechend braucht es auch eine Kraft, die "schiebt" und nicht "drückt". Beziehungsweise eine "Scherkraft", wie es in der Wissenschaft heißt. Dazu gibt es ein paar Hypothesen, zum Beispiel Berge auf dem Meeresboden, die den Druck der Wellen von oben in eine Scherkraft umlenken. Oder großräumige, lang dauernde Tief- und Hochdruckwirbel, die an der Erde schrauben. Aber all diese Effekte sind viel zu schwach, um das Ausmaß der toroidalen Schwingungen zu erklären.</p>
<p>Am Ende wird es vermutlich eine kompliziertere Erklärung sein. Irgendwie werden die sphäroidalen und toroidalen Schwingungen auf sehr komplexe Weise zusammenwirken, im Wechselspiel mit all dem anderen, das dauernd auf der Erde los ist. Aber wenn wir das mal verstanden haben, dann werden wir auch genau dieses komplexe Wechselspiel der Vorgänge besser verstehen, das unseren Planeten zu dem macht, was er ist. Und werden dann auch besser verstehen können, wie andere Planeten funktionieren. Oder es läuft umgekehrt: Denn was auf der Erde passiert sollte anderswo auch stattfinden. Zum Beispiel auf dem Mars: Der hat zwar keine Ozeane, aber zumindest ein bisschen Atmosphäre. Und vielleicht führt auch die dazu, dass der Planet schwingt; vielleicht gibt es ein "Marsbrummen". Es gab auch schon Pläne, entsprechende Messinstrumente zu unserem Nachbarplaneten zu schicken, aber daraus ist bis jetzt noch nichts geworden. Aber vielleicht finden wir auch das noch mal raus und wenn wir einen zweiten Planeten brummen hören, hilft uns das eventuell dabei, das Brummen unseres eigenen Planeten zu erklären.</p>]]>
      </content:encoded>
      <itunes:image href="https://images.podigee-cdn.net/0x,sSSOXZcufFOZESj-w-T10pZRKBXVt0X-QDOMeNzZtAcs=/https://main.podigee-cdn.net/uploads/u4340/40c425a1-9dbf-442f-9b9f-7fcde721cbe4.jpg"/>
      <itunes:episode>587</itunes:episode>
      <itunes:episodeType>full</itunes:episodeType>
      <itunes:subtitle>Alles schwingt, aber nicht esoterisch</itunes:subtitle>
      <itunes:summary>Die Erde brummt. Das hören wir nicht, aber sie tut es trotzdem. Warum sie es tut und was wir daraus lernen können, erfahrt ihr in der neuen Folge der Sternengeschichten.

Wer den Podcast finanziell unterstützen möchte, kann das hier tun: Mit PayPal (https://www.paypal.me/florianfreistetter), Patreon (https://www.patreon.com/sternengeschichten) oder Steady (https://steadyhq.com/sternengeschichten</itunes:summary>
      <itunes:explicit>no</itunes:explicit>
      <itunes:keywords>Astronomie,Universum,Sternengeschichten,Astrodicticum,Sterne,Geophysik,Erde,Seismologie,Eigenschwingung,Erdbrummen,Hum,Brummen,Schwingung,sphäroidale Schwingung,toroidale Schwingung,Kazunari Nawa,Naoki Suda,Dieter Kurrle,Black Forest Observatory,Erdbeben,Luftdruck,Wellen,Mars,Asteroseismologie</itunes:keywords>
      <itunes:author>Florian Freistetter</itunes:author>
      <enclosure length="9006860" type="audio/mpeg" url="https://audio.podigee-cdn.net/1378561-m-e27799b5f2cfe517193d70c63ba1c7bc.mp3?source=feed-scienceblogs"/>
      <itunes:duration>633</itunes:duration>
      <podcast:episode>587</podcast:episode>
    </item>
  </channel>
</rss>
"""

# Local Variables: #
# python-indent: 4 #
# End: #
